### ISSUE TITLE
cant install snippy

### ISSUE THREAD

**Issue by Noornoor440** [tseemann/homebrew-bioinformatics-linux#12]
h5-a2S91STG8WL:~ hisalf$ brew install snippy
Updating Homebrew...
==> Installing snippy from tseemann/bioinformatics-linux
Error: No available formula with the name "freebayes" (dependency of tseemann/bioinformatics-linux/snippy)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by maesaar** [comment]
@tseemann 
I get the following error:

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:12:in `<class:Snippy>'
Please report this to the tseemann/bioinformatics-linux tap!

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:13:in `<class:Snippy>'
Please report this to the tseemann/bioinformatics-linux tap!

==> Installing snippy from tseemann/bioinformatics-linux
Error: No available formula with the name "freebayes" (dependency of tseemann/bioinformatics-linux/snippy)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by tseemann** [comment]
I've moveds this into #13
