### ISSUE TITLE
:perl' is depreciated. 

### ISSUE THREAD

**Issue by lydeejeanne** [tseemann/homebrew-bioinformatics-linux#13]
I love snippy and I'm a noob for sure, so please excuse if I'm not using this forum correctly. I just got new illumina reads and although I could process the previous batch with no problems using snippy, they won't submit now. I also got this warning when I brew installed other tools, and then when I tried to install snippy again. 

Warning: Calling 'depends_on ... => :perl' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:12:in `<class:Snippy>'
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:13:in `<class:Snippy>'
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:12:in `<class:Snippy>'
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/snippy.rb:13:in `<class:Snippy>'
Please report this to the tseemann/bioinformatics-linux tap!

Just thought I'd do what the command line tells me to do :/

**Comment by tseemann** [comment]
You've come to the right place. Homebrew has undergone a major change recently (without enough notice) and many of us are stuck currently.

I assume you are running on a Mac based on the folders.  It's just a warning, you can ignore it. It should still have installed Snippy.  You still need to install the perl modules somehow yourself (this was always the case). YOu can do this with `cpan install` or `cpanm`.  

I hope this helps. If it doesn't, get back to me here and we'll figure it out.

**Comment by lydeejeanne** [comment]
Thanks for the quick reply and for creating SNIPPY, it is a great tool.
