### ISSUE TITLE
brew upgrade error

### ISSUE THREAD

**Issue by AnnaSyme** [tseemann/homebrew-bioinformatics-linux#15]
On running `brew upgrade` (Mac OSX) I get:

Error: Calling 'depends_on ... => :perl' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/tseemann/homebrew-bioinformatics-linux/Formula/snippy.rb:12:in `<class:Snippy>'
Please report this to the tseemann/bioinformatics-linux tap!

**Comment by tseemann** [comment]
Please use `brew tap brewsci/bio` instead now.
