### ISSUE TITLE
pplacer SHA256 mismatch; versioning(?)

### ISSUE THREAD

**Issue by chrisgulvik** [tseemann/homebrew-bioinformatics-linux#3]
The SHA256 is incorrect now for pplacer.

Example error from brew install:

```
brew install pplacer
==> Installing pplacer from tseemann/bioinformatics-linux
==> Downloading http://matsen.fhcrc.org/pplacer/builds/pplacer-v1.1-Linux.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 56609c052469bf7d7d238fd8ed70d06a51877a8a53e8d45272a2e9ba0a6911ed
Actual: 512da104928d4cc062100012cca4cc2fc9c279ac8d8d4cf63f770811d151caf9
```

@matsen has been releasing version one-point-ones since 2011, so my best guess is the link you currently specify gets updated with the newest alpha release and hence a different SHA256 hash.  He includes a statically compiled binary in the releases I see on GitHub, so perhaps grabbing them there would circumvent future mismatches.

https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/pplacer.rb#L11-L12
Perhaps into:

```
    url "https://github.com/matsen/pplacer/releases/download/v1.1.alpha18/pplacer-linux-v1.1.alpha18-2-gcb55169.zip"
    sha256 "4480a74a210b0b79c7da55c2a6851bb66eac411474b8d3f5109f7c5ea1cf41b8"
```

**Comment by sjackman** [comment]
I prefer to build from source when possible.
@matsen Can you please change the file name of the tarball whenever its contents change? Consider using a 3-part version number like 1.1.x.

**Comment by matsen** [comment]
A little confused here, sorry! The tarball name is built from the git SHA, so that name does change. New releases do have a 3-part version number, though the 3rd part is not an integer.

**Comment by sjackman** [comment]
The SHA256 of `http://matsen.fhcrc.org/pplacer/builds/pplacer-v1.1-Linux.tar.gz`
was 56609c052469bf7d7d238fd8ed70d06a51877a8a53e8d45272a2e9ba0a6911ed
and is now 512da104928d4cc062100012cca4cc2fc9c279ac8d8d4cf63f770811d151caf9

I see that there's a new tarball with version `v1.1.alpha18`. I'd suggest avoid alpha characters in the version number if possible. `1.1.18` is preferred.

**Comment by chrisgulvik** [comment]
Your versioning is excellent on your github page, @matsen. I was just suggesting to Torsten grabbing from your github rather than the fhcrc.org site might be the way to go.

**Comment by tseemann** [comment]
@chrisgulvik I am now getting the binary from github. (It's linux only now)

@sjackman I would build from source but the dependencies are too complex for me to deal with at the moment (OCaml etc - see http://matsen.github.io/pplacer/compiling.html)
