### ISSUE TITLE
Cutadapt installation fails

### ISSUE THREAD

**Issue by klmr** [tseemann/homebrew-bioinformatics-linux#4]
cutadapt requires a Cython dependency whose URL is no longer available. Unfortunately I don’t know enough about Homebrew and/or cutadapt to submit a fix but I’m wondering about the necessity and/or usefulness of the Cython dependency: the [cutadapt documentary](http://cutadapt.readthedocs.io/en/stable/installation.html) doesn’t mention this dependency, and `pip install cutadapt` works on my system without Cython installed (If I understand correctly, it may be using pre-compiled binaries).

I’m wondering whether there’s a straightforward way of adapting the pip installation to Homebrew.

**Comment by sjackman** [comment]
If `cython` is in fact a dependency of `cutadapt`, perhaps it could be added to https://github.com/Homebrew/homebrew-python, after which, `cutadapt` could be added to `Homebrew/science`. Well, it could be added now, but it wouldn't be testable by the BrewTestBot.

**Comment by tseemann** [comment]
@klmr I've now modernised the brew formula and upgraded to 1.11
